### ISSUE TITLE
Breadcrumbs not working in macOS Catalina

### ISSUE THREAD

**Issue by DrWebster** [ryangball/DockBuilder#4]
After building a DockBuilder package and installing it on a system running 10.15.1, DockBuilder doesn't create a breadcrumb file or log in the user profile -- thus it runs every time a user logs in and rebuilds their Dock. Changing $HOME/ in the build script to ~/ doesn't seem to make a difference.

**Comment by ryangball** [comment]
@DrWebster this should be resolved with #5. For some reason there was an issue with PlistBuddy in the build so I've switched to plutil there and it seemed like it worked fine. Also, I will probably look at optionally configuring these variables in a configuration profile in the future so that people can change preferences easily with a profile without re-deploying.
